### ISSUE TITLE
Brochure: Compilation failure on ToC -- French version

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-bipm#174]
In relation to https://github.com/metanorma/bipm-si-brochure/issues/169

For some reason, [Table of Contents](https://raw.githubusercontent.com/metanorma/bipm-si-brochure/add-cr-and-pv/sources/sections-a1-fr/00-toc.adoc) in French version is generating compilation failure.
Not the case with English version though.

Markup sample:
````
[type=toc]
== Table des matières de l’annexe 1
=== Décisions concernant l'établissement du SI (((système,international d’unités (SI)))) (((système,international d’unités (SI),création)))
* <<cgpm9e1948r6,9^e^ CGPM, 1948:pass:[<tab/>]décision d'établir le SI>>
* <<cgpm10e1954r6,10^e^ CGPM, 1954:pass:[<tab/>]décision d'adopter les six premières unités de base>>
* <<cipm1956r3,CIPM, 1956:pass:[<tab/>]décision d'adopter le nom Système international d'unités>>
...
````
Error message:
````
undefined method `[]' for nil:NilClass
C:/Ruby27-x64/lib/ruby/gems/2.7.0/ruby/2.7.0/gems/isodoc-2.1.2.1/lib/isodoc/presentation_function/section.rb:180:in `block in toc'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/ruby/2.7.0/gems/nokogiri-1.13.6-x64-mingw32/lib/nokogiri/xml/node_set.rb:234:in `block in each'
...
````

**Comment by opoudjis** [comment]
The problem citation was cipm1946r2

It has ended up rendered in the semantic XML as:

````
<p id="cipm1946r2">[%unnumbered]d
=== </p>
````

The `[%unnumbered]d` is a markup error. Fixed.

**Comment by ronaldtse** [comment]
> The `[%unnumbered]d` is a markup error. Fixed.

But the code should not crash. Is it fixed? Please reopen if not. Thanks.
