### ISSUE TITLE
Failure in macOS 2.7 build

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-bipm#184]
https://github.com/metanorma/metanorma-bipm/runs/7299291956?check_suite_focus=true

Somehow it is only 2.7 macOS that fails.

```
Failures:

  1) Metanorma::BIPM references BIPM English citations
     Failure/Error: expect(File).to receive(:exist?).with(/index\.yaml/).and_return false

       #<File (class)> received :exist? with unexpected arguments
         expected: (/index\.yaml/)
              got: ("/Users/runner/work/metanorma-bipm/metanorma-bipm/lib/metanorma/../../lib/metanorma/bipm/boilerplate-en.xml")
       Diff:
       @@ -1 +1 @@
       -[/index\.yaml/]
       +["/Users/runner/work/metanorma-bipm/metanorma-bipm/lib/metanorma/../../lib/metanorma/bipm/boilerplate-en.xml"]
     # ./spec/metanorma/base_spec.rb:1224:in `block (2 levels) in <top (required)>'
     # ./spec/spec_helper.rb:43:in `block (4 levels) in <top (required)>'
     # ./spec/spec_helper.rb:43:in `chdir'
     # ./spec/spec_helper.rb:43:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:42:in `block (2 levels) in <top (required)>'

Finished in 1 minute 18 seconds (files took 5.6 seconds to load)
64 examples, 1 failure

Failed examples:

rspec ./spec/metanorma/base_spec.rb:1223 # Metanorma::BIPM references BIPM English citations
```

**Comment by ronaldtse** [comment]
Passing now: https://github.com/metanorma/metanorma-bipm/actions/runs/2684259668

Strange.
